spring:
  thymeleaf:
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bg-workflow?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ################### mysq end ##########################
  #  zipkin:
  #    base-url: http://127.0.0.1:11008
  redis:
    ################### redis 单机版 start ##########################
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    database: 2
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms
################### mysq end ##########################

mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    blobType: BLOB
    boolValue: TRUE
    prefix:

    #flowable 取消spring boot时自动部署resource/processes中的流程文件


flowable:
  check-process-definitions: false
  #db-identity-used: true
  # 自动生成flowable相关表 第一次生成后建议关闭提高运行速度
  database-schema-update: false
  # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
  history-level: full
  #security:
  #  oauth2:
  #    ignored: /**  , /doc.html   ,/document.html
  #    token:
  #      store:
  #        type: redis

  #flowable:
  ##关闭定时任务JOB
  #  async-executor-activate: false
  common:
    app:
      #      idm-url: http://localhost:${spirng.port}/expense/
      idm-url: http://localhost:${spirng.port}/flowable-idm
  idm:
    app:
      admin:
        user-id: admin
        password: admin
        first-name: admin
        last-name: admin
#  rest:
#    app:
#      authentication-mode: verify-privilege
#  modeler:
#    app:
#      rest-enabled: true
#  database-schema-update: true


logging:
  level:
    com.quan.core: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.neusoft: DEBUG
#    com.netflix: DEBUG                    #用于心跳检测输出的日志